# Generated by Django 5.2.6 on 2025-09-21 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=4)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('to_expire', 'To Expire'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial_start_date', models.DateField(blank=True, null=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('categories_ids', models.ManyToManyField(blank=True, related_name='subscriptions', to='subscription.category')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
