# Generated by Django 5.2.6 on 2025-09-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='categories_ids',
            new_name='category_ids',
        ),
    ]
