# Generated by Django 5.2.6 on 2025-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_subscription_category_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
    ]
