# Generated by Django 5.2.6 on 2025-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_created_at_user_is_verified_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
