# Generated by Django 5.2.6 on 2025-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_code_is_used_code_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_days_before',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
