# Generated by Django 5.2.6 on 2025-11-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_image_url_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provider_id',
        ),
    ]
