# Generated by Django 5.2.6 on 2025-11-17 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_provider_remove_user_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='local', max_length=256, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=256, null=True)),
                ('proivder_email', models.CharField(max_length=256)),
                ('linked_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
