# Generated by Django 5.2.6 on 2025-11-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprovider',
            old_name='proivder_email',
            new_name='provider_email',
        ),
    ]
