# Generated by Django 5.2.6 on 2025-11-17 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_proivder_email_userprovider_provider_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='code',
            name='code_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='code',
            name='type',
            field=models.CharField(choices=[('registration', 'Registration'), ('forgot_password', 'Forgot Password')], default='registration', max_length=30),
        ),
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
