import os
from pathlib import Path
from dotenv import load_dotenv


"""
Django settings for managepro project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

from os import environ


APP_URL = "https://app.dabiri.xyz"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-*yz(s$4r9uk@--ni_hdlwom6ef=o711aes58=2%r4v83r_7p&%"
SECRET_KEY = environ.get("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = environ.get("ALLOWED_HOST", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # SYSTEM APPS
    "api",
    "user",
    "services",
    "subscription",
    # THIRD PARTY APPS
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "storages",
    "django_filters",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "managepro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "managepro.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": environ.get("POSTGRES_HOST", "localhost"),
        "PASSWORD": environ.get("POSTGRES_PASSWORD", ""),
        "USER": environ.get("POSTGRES_NAME"),
        "NAME": environ.get("POSTGRES_DB"),
        "PORT": "5432",
    }
}

APPEND_SLASH = True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "user.User"


# DJANGO SES
EMAIL_BACKEND = "django_ses.SESBackend"
AWS_SES_REGION_NAME = "us-west-1"
AWS_SES_REGION_ENDPOINT = "email.us-west-1.amazonaws.com"
SERVER_EMAIL = "mayowad43@gmail.com"
DEFAULT_FROM_EMAIL = "mayowad43@gmail.com"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ("core.renderers.CustomJSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": "subtrackpro-media",
            "region_name": "us-east-1",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AWS_DEFAULT_ACL = "public-read"  # allows anyone to access the uploaded files
AWS_QUERYSTRING_AUTH = False

# Optional media/static URL config
MEDIA_URL = "/media/"
STATIC_URL = "/static/"


CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Lagos"

CELERY_BEAT_SCHEDULE = {
    "update-subscription-statuses-daily": {
        "task": "subscription.tasks.to_expire_subscription_status_change",
        "schedule": timedelta(minutes=1),
    },
    "expire-subscription-statuses-daily": {
        "task": "subscription.tasks.expire_subscription_status_change",
        "schedule": crontab(hour=0, minute=0),
    },
    "clear-used-otp-monthly": {
        "task": "user.tasks.clear_used_otp",
        "schedule": crontab(hour=0, minute=0),
    },
}

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = ["http://localhost:5173", "http://localhost:3000", APP_URL]
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = environ.get("SESSION_COOKIE_SECURE", "False") == "True"
CSRF_COOKIE_SECURE = environ.get("CSRF_COOKIE_SECURE", "False") == "True"


GOOGLE_CLIENT_ID = environ.get("GOOGLE_CLIENT_ID")

RESEND_API_KEY = environ.get("RESEND_API_KEY")

RESEND_EMAIL_FROM = "SubtrackPro Support <support@dabiri.xyz>"


OTP_SECRET_KEY = "9e0314749b8eaaa7e251866091513d72f52e6c536f7097b336c3ba99d0741b86"
